# -*- coding: utf-8 -*-
"""Comparison Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aTwGVAK57tL9svE355u0mQxADkM8OPQc
"""

#Comparing Variables
'''
Numerical Values
x > 30 #Greater Than
x < 30 #Less than
x >= 30 #Greater than or equal to
x <= 30 #Less than or equal to
x == 30 #Equal to
x != 30 #Not equal to

Boolean
x = True

Strings
x == 'string' #Equals to 
x != 'string' #Not equals to

'''

x = 10

if x > 30:
  print('x is too high, above 30')

"""Comparison example in Program/Challenges.ipynb"""