# -*- coding: utf-8 -*-
"""If & Logical Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AeFupvPBSC24Paqyj05b--Jd-NGECUBj
"""

#if statements with boolean

bvalue = False
evalue = True
if bvalue: # = True is not needed
  print('bvalue is true')

elif evalue: 
  print('evalue is true')

else: 
  print('bvalue is false')

#Logical operators
#use boolean

#and
avalue = True
bvalue = True

if avalue and bvalue: 
  print('both requirements satisfied')

else:
  print('criterion not met')

#or --> at least one must be met
cvalue = True 
dvalue = True

if cvalue or dvalue:
  print('At least one criteria met')

else:
  print("Criterias were not met")

#and not --> MUST not meet one criteria 
evalue = True
fvalue = False

if evalue and not fvalue:
  print('Requirements statisfied')

elif fvalue:
  print('fvalue met, requirements failed')

else: 
  print('evalue not met, requirements failed')