# -*- coding: utf-8 -*-
"""Functions, Parameters and Return.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hwcSpK10IdVVkEiEdvoKiiOZ0Zb0ZYgZ
"""

def greet_user():
  print("Hello!")
  print("Welcome to Python!")

greet_user()

#Parameters
def say_hello(name, last_name): 
  print(f"Hello! {name}, {last_name}")
  print("Welcome!")

value = input("What is your fullname? ")
fullname = value.split(" ")

say_hello((fullname[0]), (fullname[1])) #must have two arguements: name, last_name in the same order
say_hello(last_name=fullname[1], name=fullname[0]) #Keyword arguments, does not have to be in order but must be defined by variables "name=fullname[0]"

def square(x):
  return x * x

result = square(3)
print(result)