# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Ub3gGUU8zXXmj-DMBWaBthkRquIk1cV
"""

#Variables
variable = 10
float = 3.9

#String
string = 'Hello'

#Boolean
boolean_value = False
boolean_value = True

#Using the Global Function/Accessing variables declared outside of functions
integer = 1

def modify():
    integer = 2
    
def main():
    print(integer)
    
main()