# -*- coding: utf-8 -*-
"""Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zzYCv7kUT8KoUlXCFbLtlLd_dPXyQmOe
"""

#Double quotes " and singles quotes are not the same '
#string = "hello he said 'this is cool' and left" (correct)
#string = 'hello he said "this is cool" and left' (correct)

string = '''
Hello this is a multiline string

it even includes spacing

goodbye
'''

print(string)

#Indexing
string = 'My name is Jayden Soh'
x = 5
string_multiplied = '*' * x
#the same output as print('*****')
print(string_multiplied)
##########01 2345 67 89....
string_indexed_first_character = string[0]
string_indexed_last_character = string[-1]
string_indexed_second_last_character = string[-2]
string_indexed_first_to_third_character = string[0:3] #or string[:3] "My "
