# -*- coding: utf-8 -*-
"""Formatted_Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtJ73b-wFX4gvOwgh4T6XLewdNd4nx9c
"""

first = 'John'
last = 'Smith'
#Desired Message: John [Smith] is a coder

formatted_string = f'{first} [{last}] is a coder' #f''
print(formatted_string)