# -*- coding: utf-8 -*-
"""Modifying Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OZ_tmtcBjfss9hTvvP3CsC5MALcnnux4
"""

string = 'Identifying my profile'
print(string[0]) #First letter of the string
num_of_characters = len(string)
uppercase_string = string.upper() #.upper
lowercase_string = string.lower() #.lower
finding_first_letter = string.find('I') #0 (position 0)
finding_first_word = string.find('profile') #14 (position 14)

replacing_word = string.replace('Identifying', 'Searching') #String = Searching my profile
replace_first_letter = string.replace('e', 'i') #String 'Idintifying my profile'
boolean = ('profile' in string) #True

string.split(" ") #Splits the string at every " "
#output ["Identifying", "my", "profile"]

# print(string.find("asdas")) if letter not found returns -1