# -*- coding: utf-8 -*-
"""Mathematical Operations and Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1okivgW0J6anTMsyQMf1wddqZ2Cv_82ng
"""

import math 

addition = 10 + 3 
subtraction = 10 - 3
multiplication = 10 * 3 
division = 10 / 3
exponents = 10 ** 3 
integer_of_division = 10 // 3
remainder_of_division = 10 % 3

x = 10
########
x += 3
#is the same as
x = x + 3

#The operators are in order (exponents executed first, brackets can change piority)

x = 2.3
rounding = round(x) 
rounding_to_decimal_places = round(x, 2) #value two can be changed to number of decimal places
absolute = abs(x) #negative to positive, positive to negative (-2.3)
round_down = math.floor(2.9) #2
round_up = math.ceil(x) #3