# -*- coding: utf-8 -*-
"""Input & Outputs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/125o4AyPlyb5_5HrUoKs5G6UBp_CuRiBN
"""

#input
input()

string = input('What is your name? ')
string_prefer = input('What is your favorite color? ')
print(string + ' likes ' + string_prefer)