# -*- coding: utf-8 -*-
"""Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16m7jzkGsxXYTSaDr_LQWi18IwLCN37VM
"""

names = ['John', 'Mary', 'Bob', 'Keevan', 'Jaron', 'Davion']

#Indexing
first_value = names[0]
second_value = names[1]
last_value = names[-1]

second_value_onwards = names[1:]
second_value_to_fifth_value = names[1:4]

print(second_value_onwards)

#Modification
names[0] = 'Jon' #First value from John --> Jon

#2D Lists

matrix  = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

#A row is a list

for row in matrix: 
  for item in row:
    print(item)
    
#finding specific values
value = matrix[0][1] # first row, second value
print(value)

#editing a matrix
matrix[0][1] = 3
print(matrix[0][1])

#Modifying Lists  

numbers = [1, 2, 3, 4, 5, 6, 7]
strings = ['a', 'c', 'b']

numbers.append(8) #adds value/item to the end of the list
numbers.insert(1, 8) #adds value/item to the given index numbers.insert(index position, object)
numbers.remove(8) #removes the first '8' value from the list (ValueError if '8' is not present)
numbers.clear() #clears the WHOLE LIST
numbers = [1, 2, 3, 4, 5, 6, 7]
numbers.pop() #removes the last item in the list

numbers.index(5) #finds the position of the first '5' value in the list (ValueError if 5 is not in the list)
boolean_value = 50 in numbers #if 50 is in the list, it will return True, if not it will be False
numbers.count(8) #finds how many times '8' appears

numbers.sort() #sorts the list according to ascending order for numbers
strings.sort() #sorts the list according to alphabetical order
numbers.reverse() #sorts the list according to a desending order for numbers
strings.reverse() #sorts the list according to a desending alphabetical order

numbers2 = numbers.copy() #makes a copy of the 'numbers' list 

print(numbers)

lists = ['hi', 'bye', 'supercra', 'a']
lists.sort()
print(lists)