# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otq7_6pljnJOU6NbU3HD8G-o2UH28SKX
"""

#Defining Dictionaries
data = {
    'name' : 'John Smith',
    'age' : 30,
    'verified' : True,
    "favorite colors": ["red", "white", "blue"] #it is even possible for lists to be stored in dictionaries
    }

#Getting definitions
print("Getting definitions")
#this will bring the definition or object stored 
print(data["name"]) 
print(data["age"])
print(data["verified"])
print(data["favorite colors"])
print("")


#KeyError
#print(data["unknown"]) #However, if the value does not exist, KeyError will be raised (its now commented so other parts of the code can run)

#Avoiding KeyError
print("Avoiding KeyError")
print(data.get("name")) #using data.get() !It is no longer in [] but instead in ()
print(data.get("age"))
print(data.get("verified"))
print(data.get("unknown")) #will return "None" instead of an error
print("")

#Modifying dictionaries
print("Modifying Dictionaries")
data["age"] = 20 #'age' value is changed
data["birthdate"] = "January 15th 1975" #a new value is created "birthdate"
print(data.get("age"))
print(data.get("birthdate"))
print("")

#Other commands
print("Others")
print(len(data)) #Length of dictionary (how many items) --> name, age, verified, birthdate (4)
data2 = dict(name = "John", age = 36, country = "Norway") #Making a dictionary

