# -*- coding: utf-8 -*-
"""Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N8QmUtJ5SPRGcgCVatpTaqqwFW4o_1hX
"""

#While condition comparison
x = 0

while x < 10:
  x += 1 
  print(x)

'''
while True:

is a forever repeating loop since it is ALWAYS true
'break' is needed to break out of the loop


while <condition> (is true):

is a condition based loop since it might not always be true
'''

#For Loops
#used for iterating over items of a collection eg String

for item in 'Python':
  #item will be set to the first character in the first iteration
  print(item)
  #repeat 6 times
  #each time printing one character one by one


#for loops for lists
x = ['Number1', 'Number2', 'Number3']

for item in x:
  print(item)


for item in range(10): #can be (5,10) as well
  #repeat 10 times --> 0-10
  print(item)