# -*- coding: utf-8 -*-
"""Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsEH1t6Bq1VdumsC4X336pF4B5u7NyW0
"""

tuples = (1, 2, 3) #Parenthesis is used instead of square brackets   

'''
Tuples cannot be modified unlike lists.
'''

print(tuples[0])