# -*- coding: utf-8 -*-
"""Type Conversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dG4E7VOafRhTTz1ZdRYsGqfbMMBlJ4h5
"""

#Types
int() #string --> int
float() #string --> Float
bool() #string --> Boolean
type() #type of variable

#Example
birth_year = int(input('Birth year: '))
age = 2022 - birth_year
print(age)