# -*- coding: utf-8 -*-
"""Unpacking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GdyeOt-stZourLKIubo4oKb7LTPOTMd
"""

numbers = [1, 2, 3]

#instead of
print(numbers[0] * numbers[1] * numbers[2])

#or
x0 = numbers[0]
x1 = numbers[1]
x2 = numbers[2]

x0 * x1 * x2

#use this
x, y, z = numbers 
print(x * y * z)

'''
python will assign the first variable to the first value stored in the 'numbers' list
also works for tuples
'''