# -*- coding: utf-8 -*-
"""Exceptions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BPb-4CqBfW0LG969KD3IJ08aqZleelLH
"""

#Used to handle errors to prevent the code from crashing
'''
try: 

except <Error>:
  runs whatever code follows after

'''

try: 
  age = int(input("What is your age: "))

except ValueError:
  print("Invalid input, input should be a number")